### ISSUE TITLE
Serve static pages using Flask

### ISSUE THREAD

**Issue by bass-dandy** [rioscesar/Music-Mecca#19]
Doing so will allow us to use SSI for reusable DOM elements (eg the navbar).

**Comment by rioscesar** [comment]
We could go a step further and make a single page application

**Comment by bass-dandy** [comment]
That's a good goal I think but we should probably walk before we run

**Comment by bass-dandy** [comment]
But I don't see why we wouldn't be able to do AJAJ all the way down eventually

**Comment by rioscesar** [comment]
👍
