### ISSUE TITLE
Labels (all) API call returns internal server error

### ISSUE THREAD

**Issue by bass-dandy** [rioscesar/Music-Mecca#62]
Navigating to downing.club/api/labels returns:

{"message": "Internal Server Error"}

Should return a list of all labels. Searching for a label by ID (eg by going to downing.club/api/labels/1) works however.

**Comment by KaelenHaag1** [comment]
I believe Cesar fixed that in 8a76c0328093c4018a93d2b99a672fe19f32b968?

Yup fixed
