### ISSUE TITLE
API calls for Artist

### ISSUE THREAD

**Issue by rioscesar** [rioscesar/Music-Mecca#7]

**Comment by KaelenHaag1** [comment]
for the basic artist api calls
/{artist_id}
/artist_name

Then we can do more specific api calls to get that artists details like releases. awards, bio, etc 
/{artist_id}/bio
/artist_name/awards

Not sure exactly the how the formatting for these are supposed to be. Is this correct?

**Comment by rioscesar** [comment]
For anything that's not a model there's no need to call it individually since it will be returned by the artist object. 

Doing a simple /artist/{artist_id} will return everything in the artist table as json. Then in the front end you just read the json and manipulate it as needed.

**Comment by KaelenHaag1** [comment]
Ah yeah forgot the artist/!

I get why there's no need to have api calls for non model data like bio, name, photo but we would want to be able to individually call model data (Label, Release, Award) of an artist? Or do we just want the user to worry about extracting that data from the JSON?

**Comment by rioscesar** [comment]
right now it's all up in air, routes haven't been decided on but it can most def be possible
